[package]
name = "sys_mets1"
version = "0.1.0"
authors = ["recombinant <gituser@recombinant.me.uk>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winuser","winbase"] }
sys_mets_data = { path = "../sys_mets_data" }
