[package]
name = "checker1"
version = "0.1.0"
authors = ["recombinant <gituser@recombinant.me.uk>"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winuser", "winbase", "windowsx", ] }
extras = { path = "../../extras" }
